version: '3.7'
services:
    web:
        container_name: dev_backend
        build: ./
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db

    db:
        container_name: dev_db
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: "tennis_db"
            POSTGRES_PASSWORD: "123passw"
            POSTGRES_USER: "tennis_user"

volumes:
    postgres_data: