# Generated by Django 4.0.3 on 2022-03-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_surface_alter_game_date_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='date_game',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='result_game',
            new_name='result',
        ),
        migrations.AddField(
            model_name='player',
            name='pro',
            field=models.BooleanField(default=False),
        ),
    ]
